name: digitor
description: Production Flutter UI for DigitorEngine.
publish_to: "none"
version: 0.2.4+6

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  digitor_engine_ffi:
    git:
      url: https://github.com/Tajuli/DigitorEngine.git
      path: dart/digitor_engine_ffi
      ref: e26d1f59ac0630ead1861920e0560d1be25ecee9
  file_selector: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
