name: digitor
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  file_picker: ^10.3.3
  video_thumbnail: ^0.5.6
  video_player: ^2.10.0
  # Windows implementation for the official video_player API.
  video_player_win: ^3.2.1
  video_compress: ^3.1.4
  just_audio: ^0.10.6
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
