name: digitor
description: Production Flutter UI for DigitorEngine.
publish_to: "none"
version: 0.2.3+5

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  digitor_engine_ffi:
    git:
      url: https://github.com/Tajuli/DigitorEngine.git
      path: dart/digitor_engine_ffi
      ref: 4db9bed7f14e146bf124f78c8c3971b1620a1b1e
  file_selector: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
