import 'package:flutter/rendering.dart';
import 'package:flutter/material.dart';
import '../../application/project_controller.dart';
import '../../application/timeline_controller.dart';
import 'timeline_canvas.dart';
import 'timeline_constants.dart';
import 'timeline_scroll_controller.dart';
import 'track_header_column.dart';
import '../../application/playback_controller.dart';

/// A single horizontal canvas keeps ruler, clips, and playhead perfectly aligned.
class TimelineView extends StatefulWidget { const TimelineView({super.key, required this.controller, required this.timelineController, required this.playbackController}); final ProjectController controller; final TimelineController timelineController; final PlaybackController playbackController; @override State<TimelineView> createState() => _TimelineViewState(); }
class _TimelineViewState extends State<TimelineView> { late final TimelineScrollController _scroll; bool _manualScroll = false; @override void initState() { super.initState(); _scroll = TimelineScrollController()..horizontal.addListener(_onScroll); widget.playbackController.addListener(_playbackTick); } void _onScroll() { if (mounted) setState(() {}); } void _playbackTick() { if (!mounted) return; widget.timelineController.setPosition(widget.playbackController.position); if (!_manualScroll && widget.playbackController.isPlaying && _scroll.horizontal.hasClients) { final x = widget.timelineController.position.inMicroseconds / Duration.microsecondsPerSecond * widget.timelineController.pixelsPerSecond; final limit = _scroll.horizontal.offset + _scroll.horizontal.position.viewportDimension * TimelineConstants.viewportFollowThreshold; if (x > limit) _scroll.horizontal.jumpTo((x - _scroll.horizontal.position.viewportDimension * TimelineConstants.viewportFollowThreshold).clamp(0.0, _scroll.horizontal.position.maxScrollExtent)); } } @override void dispose() { widget.playbackController.removeListener(_playbackTick); _scroll.horizontal.removeListener(_onScroll); _scroll.dispose(); super.dispose(); }
@override Widget build(BuildContext context) => AnimatedBuilder(animation: Listenable.merge([widget.controller, widget.timelineController]), builder: (context, _) => Column(children: [_Toolbar(controller: widget.timelineController), const Divider(height: 1), Expanded(child: NotificationListener<UserScrollNotification>(onNotification: (n) { _manualScroll = n.direction != ScrollDirection.idle; return false; }, child: Stack(children: [TimelineCanvas(projectController: widget.controller, timelineController: widget.timelineController, scrollController: _scroll, playbackController: widget.playbackController), IgnorePointer(child: Transform.translate(offset: Offset(_scroll.horizontal.hasClients ? _scroll.horizontal.offset : 0, 0), child: TrackHeaderColumn(tracks: widget.controller.tracks)))])))])); }
class _Toolbar extends StatelessWidget { const _Toolbar({required this.controller}); final TimelineController controller; @override Widget build(BuildContext context) => SizedBox(height: TimelineConstants.toolbarHeight, child: Row(children: [const SizedBox(width: TimelineConstants.headerWidth), IconButton(tooltip: 'Zoom out', onPressed: controller.zoomOut, icon: const Icon(Icons.remove)), Text('${(controller.pixelsPerSecond / TimelineConstants.pixelsPerSecond * 100).round()}%'), IconButton(tooltip: 'Zoom in', onPressed: controller.zoomIn, icon: const Icon(Icons.add)), const Spacer(), TextButton(onPressed: () => controller.setPosition(Duration.zero), child: const Text('00:00'))])); }
